queue_rules:
  merge_method: squash
        
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
